source 'https://rubygems.org'

gem 'rails', '4.1.7'
gem 'activerecord-jdbcsqlite3-adapter', '1.3.13'
gem 'therubyrhino', '2.0.4'

gem 'jar-dependencies', '~> 0.1.11'

group :test do
  gem "rspec-rails", "~> 2.14.0"
end
